version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - run: pip install -r requirements.txt
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
