version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "./requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "./requirements.txt" }}
      - run:
        name: create venv and install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - run: lektor build -f
