version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs:python3.8-nodejs16
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: npm install -g webpack@4.0.0
      - run: lektor build -f webpack & pwd
      - run: lektor deploy ghpages


