version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build:
    docker:
      - image: thejoeejoee/thesaurus-webpack
    steps:
      - checkout
      - run: python get-pip.py
      - run: pip install -r requirements.txt
      - run: npm install -g webpack@4.0.0
      - run: npm install webpack-cli
      - run: lektor plugins add webpack-support
      - run: lektor build -f webpack
