version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: lektor plugins add webpack-support
      - run: lektor build -f webpack
