version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: sudo apt install webpack
      - run: lektor plugins add webpack-support
      - run: lektor build -f webpack
