version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - run:
        name: create venv and install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - run: lektor build -f
