version: 2.1
orbs:
  python: circleci/python@1.4.0
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - node/install-packages:
        override-ci-command: npm install
      - run: pip install -r requirements.txt
      - run: lektor plugins add webpack-support
      - run: lektor build -f webpack
