version: 2.1
orbs:
  python: circleci/python@1.4.0
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: npm install -g webpack@4.0.0
      - run: npm install webpack-cli
      - run: ls
      - run: lektor plugins add webpack-support
      - run: ls & lektor build -f webpack
